--- Smoke test: verify test framework and core modules load correctly.

local Constants = require("src/Constants")
local GameState = require("src/GameState")
local TurnManager = require("src/TurnManager")
local IncomeTrack = require("src/IncomeTrack")
local TestHelpers = require("tests/test_helpers")

describe("Test Framework", function()
    it("should run basic assertions", function()
        expect(1 + 1).toBe(2)
        expect(true).toBeTrue()
        expect(nil).toBeNil()
    end)
end)

describe("GameState.new", function()
    it("should create a 2-player state", function()
        local state = GameState.new(2)
        expect(state.era).toBe(Constants.Era.CANAL)
        expect(state.round).toBe(1)
        expect(#state.turnOrder).toBe(2)
    end)

    it("should give each player $17 and income level 10", function()
        local state = GameState.new(2)
        local color = state.turnOrder[1]
        local player = GameState.getPlayer(state, color)
        expect(player.money).toBe(Constants.INITIAL_MONEY)
        expect(player.incomeLevel).toBe(Constants.INITIAL_INCOME)
    end)
end)

describe("TestHelpers", function()
    it("should create state with player overrides", function()
        local state, player, color = TestHelpers.createStateWithPlayer({ money = 50 })
        expect(player.money).toBe(50)
    end)
end)

describe("IncomeTrack", function()
    it("should return correct income for positive levels", function()
        expect(IncomeTrack.levelToIncome(10)).toBe(10)
        expect(IncomeTrack.levelToIncome(0)).toBe(0)
    end)

    it("should return negative income for negative levels", function()
        expect(IncomeTrack.levelToIncome(-5)).toBe(-5)
    end)
end)

describe("TurnManager.incomePhase", function()
    it("should add money for positive income", function()
        local state, player, color = TestHelpers.createStateWithPlayer({ money = 10, incomeLevel = 5 })
        TurnManager.incomePhase(state)
        expect(player.money).toBe(15)
    end)

    it("should deduct money for negative income", function()
        local state, player, color = TestHelpers.createStateWithPlayer({ money = 10, incomeLevel = -3 })
        TurnManager.incomePhase(state)
        expect(player.money).toBe(7)
    end)

    it("should return shortfall when cannot pay negative income (VP not immediately deducted)", function()
        local state, player, color = TestHelpers.createStateWithPlayer({ money = 1, incomeLevel = -5, vp = 10 })
        local shortfalls = TurnManager.incomePhase(state)
        expect(player.money).toBe(0)
        expect(player.vp).toBe(10) -- VP not deducted yet (pending interactive resolution)
        expect(#shortfalls).toBe(1)
        expect(shortfalls[1].amount).toBe(4) -- owed 5, had 1, shortfall 4
    end)
end)
