--- Tests for Tile module, especially era-based brewery resource production.

local Tile = require("src/Tile")
local Constants = require("src/Constants")

describe("Tile.newWithResources - brewery era-based resources", function()
    it("brewery level 1 with era=canal should produce 1 beer", function()
        local tile = Tile.newWithResources(Constants.Industry.BREWERY, 1, Constants.Era.CANAL)
        expect(#tile.resources).toBe(1)
        expect(tile.resources[1]).toBe(Constants.Resource.BEER)
        expect(tile.produces).toBe(1)
    end)

    it("brewery level 1 with era=rail should produce 2 beer", function()
        local tile = Tile.newWithResources(Constants.Industry.BREWERY, 1, Constants.Era.RAIL)
        expect(#tile.resources).toBe(2)
        expect(tile.resources[1]).toBe(Constants.Resource.BEER)
        expect(tile.resources[2]).toBe(Constants.Resource.BEER)
        expect(tile.produces).toBe(2)
    end)

    it("brewery level 3 with era=rail should produce 2 beer", function()
        local tile = Tile.newWithResources(Constants.Industry.BREWERY, 3, Constants.Era.RAIL)
        expect(#tile.resources).toBe(2)
        expect(tile.resources[1]).toBe(Constants.Resource.BEER)
        expect(tile.resources[2]).toBe(Constants.Resource.BEER)
        expect(tile.produces).toBe(2)
    end)

    it("brewery level 1 with nil era should default to 1 beer (canal)", function()
        local tile = Tile.newWithResources(Constants.Industry.BREWERY, 1)
        expect(#tile.resources).toBe(1)
        expect(tile.resources[1]).toBe(Constants.Resource.BEER)
        expect(tile.produces).toBe(1)
    end)

    it("brewery should auto-flip on build", function()
        local tile = Tile.newWithResources(Constants.Industry.BREWERY, 1, Constants.Era.CANAL)
        expect(tile.flipped).toBeTrue()
    end)
end)

describe("Tile.newWithResources - coal/iron unchanged by era", function()
    it("coal mine level 1 with era=rail should use BoardData produces (2)", function()
        local tile = Tile.newWithResources(Constants.Industry.COAL, 1, Constants.Era.RAIL)
        expect(#tile.resources).toBe(2)
        expect(tile.resources[1]).toBe(Constants.Resource.COAL)
        expect(tile.resources[2]).toBe(Constants.Resource.COAL)
        expect(tile.produces).toBe(2)
    end)

    it("iron works level 1 with era=rail should use BoardData produces (4)", function()
        local tile = Tile.newWithResources(Constants.Industry.IRON, 1, Constants.Era.RAIL)
        expect(#tile.resources).toBe(4)
        expect(tile.resources[1]).toBe(Constants.Resource.IRON)
        expect(tile.produces).toBe(4)
    end)

    it("coal mine level 3 with era=canal should use BoardData produces (4)", function()
        local tile = Tile.newWithResources(Constants.Industry.COAL, 3, Constants.Era.CANAL)
        expect(#tile.resources).toBe(4)
        expect(tile.produces).toBe(4)
    end)
end)
