local SnapMap = {}

SnapMap.byTag = {}      -- tag string → { position, rotation, snapIndex }
SnapMap.bySlotId = {}   -- "Birmingham_1" → snap data
SnapMap.byLinkId = {}   -- "Birmingham-Coventry" → snap data
SnapMap.byCityCenter = {} -- "Birmingham" → Vector (center of all slots)

--- Scan a board object's snap points and build all mappings
-- Snap point tags follow format:
--   "city_Birmingham_1" for building slots
--   "link_Birmingham-Coventry" for route links
function SnapMap.buildFromObject(boardObject)
    SnapMap.byTag = {}
    SnapMap.bySlotId = {}
    SnapMap.byLinkId = {}

    local snaps = boardObject.getSnapPoints()
    for i, snap in ipairs(snaps) do
        local tag = snap.tags and snap.tags[1] or nil
        if tag then
            local data = {
                position = boardObject.positionToWorld(snap.position),
                rotation = snap.rotation,
                snapIndex = i,
                tag = tag,
            }
            SnapMap.byTag[tag] = data

            if tag:sub(1, 5) == "city_" then
                local slotId = tag:sub(6)
                SnapMap.bySlotId[slotId] = data
            elseif tag:sub(1, 5) == "link_" then
                local linkId = tag:sub(6)
                SnapMap.byLinkId[linkId] = data
            end
        end
    end
end

--- Build slot mappings from hardcoded positions.
-- Positions measured from the reference mod's save-level snap points.
-- This avoids using TTS Tags (which restrict snap behavior).
function SnapMap.buildFromGlobal()
    SnapMap.byTag = {}
    SnapMap.bySlotId = {}
    SnapMap.byLinkId = {}

    -- Hardcoded: snap point world position -> BoardData slot ID
    -- Generated by scripts/build_snap_tags.py
    local SLOT_POSITIONS = {
        -- Belper (3 slots)
        { id = "Belper_1", pos = Vector(7.299, 0.96, 13.939) },
        { id = "Belper_2", pos = Vector(8.955, 0.96, 13.939) },
        { id = "Belper_3", pos = Vector(10.584, 0.96, 13.939) },
        -- Birmingham (4 slots)
        { id = "Birmingham_1", pos = Vector(3.743, 0.96, -6.824) },
        { id = "Birmingham_2", pos = Vector(3.764, 0.96, -5.244) },
        { id = "Birmingham_3", pos = Vector(5.386, 0.96, -6.817) },
        { id = "Birmingham_4", pos = Vector(5.414, 0.96, -5.223) },
        -- Burton-on-Trent (2 slots — 3rd snap point skipped, not a game slot)
        { id = "Burton-on-Trent_1", pos = Vector(10.171, 0.96, -7.885) },
        { id = "Burton-on-Trent_2", pos = Vector(10.990, 0.96, -6.282) },
        -- Cannock (2 slots)
        { id = "Cannock_1", pos = Vector(-1.692, 0.96, 1.758) },
        { id = "Cannock_2", pos = Vector(-0.032, 0.96, 1.781) },
        -- Coalbrookdale (3 slots)
        { id = "Coalbrookdale_1", pos = Vector(-10.200, 0.96, -2.829) },
        { id = "Coalbrookdale_2", pos = Vector(-9.368, 0.96, -1.263) },
        { id = "Coalbrookdale_3", pos = Vector(-8.530, 0.96, -2.829) },
        -- Coventry (3 slots — 3rd position estimated between/above existing two)
        { id = "Coventry_1", pos = Vector(2.114, 0.96, -10.818) },
        { id = "Coventry_2", pos = Vector(3.773, 0.96, -10.818) },
        { id = "Coventry_3", pos = Vector(2.944, 0.96, -9.300) },
        -- Derby (3 slots)
        { id = "Derby_1", pos = Vector(8.429, 0.96, 8.222) },
        { id = "Derby_2", pos = Vector(9.234, 0.96, 9.794) },
        { id = "Derby_3", pos = Vector(10.044, 0.96, 8.203) },
        -- Dudley (2 slots)
        { id = "Dudley_1", pos = Vector(-6.169, 0.96, -9.017) },
        { id = "Dudley_2", pos = Vector(-4.555, 0.96, -9.001) },
        -- Kidderminster (2 slots)
        { id = "Kidderminster_1", pos = Vector(-3.722, 0.96, -5.508) },
        { id = "Kidderminster_2", pos = Vector(-2.096, 0.96, -5.496) },
        -- Leek (2 slots)
        { id = "Leek_1", pos = Vector(-7.521, 0.96, 8.399) },
        { id = "Leek_2", pos = Vector(-5.888, 0.96, 8.390) },
        -- Nuneaton (2 slots) — swapped with Uttoxeter per board verification
        { id = "Nuneaton_1", pos = Vector(9.378, 0.96, -3.402) },
        { id = "Nuneaton_2", pos = Vector(11.021, 0.96, -3.395) },
        -- Redditch (2 slots)
        { id = "Redditch_1", pos = Vector(-5.710, 0.96, -13.405) },
        { id = "Redditch_2", pos = Vector(-4.074, 0.96, -13.389) },
        -- Stafford (2 slots)
        { id = "Stafford_1", pos = Vector(1.098, 0.96, 14.439) },
        { id = "Stafford_2", pos = Vector(2.732, 0.96, 14.424) },
        -- Stoke-on-Trent (3 slots)
        { id = "Stoke-on-Trent_1", pos = Vector(-3.885, 0.96, 11.988) },
        { id = "Stoke-on-Trent_2", pos = Vector(-3.022, 0.96, 13.529) },
        { id = "Stoke-on-Trent_3", pos = Vector(-2.225, 0.96, 11.988) },
        -- Stone (2 slots)
        { id = "Stone_1", pos = Vector(-4.259, 0.96, 5.207) },
        { id = "Stone_2", pos = Vector(-2.637, 0.96, 5.223) },
        -- Tamworth (2 slots)
        { id = "Tamworth_1", pos = Vector(1.520, 0.96, 8.990) },
        { id = "Tamworth_2", pos = Vector(3.181, 0.96, 8.972) },
        -- Uttoxeter (2 slots) — swapped with Nuneaton per board verification
        { id = "Uttoxeter_1", pos = Vector(5.674, 0.96, 4.249) },
        { id = "Uttoxeter_2", pos = Vector(7.303, 0.96, 4.249) },
        -- Walsall (2 slots)
        { id = "Walsall_1", pos = Vector(0.314, 0.96, -2.130) },
        { id = "Walsall_2", pos = Vector(1.955, 0.96, -2.145) },
        -- Wolverhampton (2 slots)
        { id = "Wolverhampton_1", pos = Vector(-5.350, 0.96, -1.340) },
        { id = "Wolverhampton_2", pos = Vector(-3.743, 0.96, -1.347) },
        -- Worcester (2 slots)
        { id = "Worcester_1", pos = Vector(6.208, 0.96, -0.016) },
        { id = "Worcester_2", pos = Vector(7.827, 0.96, 0.012) },
    }

    local count = 0
    local cityAccum = {}  -- cityName -> { sumX, sumZ, n }
    for _, entry in ipairs(SLOT_POSITIONS) do
        local data = {
            position = entry.pos,
            rotation = { x = 0, y = 180, z = 0 },
            tag = "city_" .. entry.id,
        }
        SnapMap.bySlotId[entry.id] = data
        SnapMap.byTag["city_" .. entry.id] = data
        count = count + 1

        -- Accumulate city center
        local cityName = entry.id:match("^(.+)_%d+$")
        if cityName then
            if not cityAccum[cityName] then
                cityAccum[cityName] = { sumX = 0, sumZ = 0, n = 0 }
            end
            local a = cityAccum[cityName]
            a.sumX = a.sumX + entry.pos.x
            a.sumZ = a.sumZ + entry.pos.z
            a.n = a.n + 1
        end
    end

    -- Compute city centers
    SnapMap.byCityCenter = {}
    for cityName, a in pairs(cityAccum) do
        SnapMap.byCityCenter[cityName] = Vector(a.sumX / a.n, 0.96, a.sumZ / a.n)
    end

    -- Add merchant city centers (no building slots, but needed for link matching)
    -- Positions from tagged merchant snap points in the save file
    SnapMap.byCityCenter["Shrewsbury"]  = Vector(-14.439, 0.96, -3.011)
    SnapMap.byCityCenter["Gloucester"]  = Vector(3.702, 0.96, -14.548)
    SnapMap.byCityCenter["Oxford"]      = Vector(11.523, 0.96, -11.985)
    SnapMap.byCityCenter["Warrington"]  = Vector(-7.762, 0.96, 12.550)
    SnapMap.byCityCenter["Nottingham"]  = Vector(14.237, 0.96, 10.424)

    -- Link snap point positions → BoardData link IDs
    -- Generated from save file snap points (rotZ=180) matched to nearest link midpoints
    local LINK_POSITIONS = {
        { id = "Redditch-Dudley",             pos = Vector(-5.660, 0.96, -11.507) },
        { id = "Redditch-Birmingham",         pos = Vector(-0.662, 0.96, -10.045) },
        { id = "Kidderminster-Dudley",        pos = Vector(-5.175, 0.96, -7.144) },
        { id = "Kidderminster-Coalbrookdale", pos = Vector(-8.499, 0.96, -6.754) },
        { id = "Coalbrookdale-Shrewsbury",    pos = Vector(-11.754, 0.96, -1.317) },
        { id = "Coalbrookdale-Wolverhampton", pos = Vector(-7.388, 0.96, -1.276) },
        { id = "Gloucester-Redditch",         pos = Vector(-2.077, 0.96, -14.461) },
        { id = "Oxford-Redditch",             pos = Vector(0.295, 0.96, -12.101) },
        { id = "Coventry-Oxford",             pos = Vector(5.738, 0.96, -11.260) },
        { id = "Dudley-Wolverhampton",        pos = Vector(-4.262, 0.96, -3.716) },
        { id = "Wolverhampton-Walsall",       pos = Vector(-1.709, 0.96, -1.495) },
        { id = "Dudley-Birmingham",           pos = Vector(0.718, 0.96, -5.985) },
        { id = "Walsall-Birmingham",          pos = Vector(1.976, 0.96, -4.400) },
        { id = "Birmingham-Coventry",         pos = Vector(3.980, 0.96, -8.918) },
        { id = "Burton-on-Trent-Coventry",    pos = Vector(7.655, 0.96, -9.164) },
        { id = "Coventry-Nuneaton",           pos = Vector(7.749, 0.96, -7.477) },
        { id = "Birmingham-Nuneaton",         pos = Vector(7.479, 0.96, -4.938) },
        { id = "Birmingham-Worcester",        pos = Vector(6.758, 0.96, -2.971) },
        { id = "Nuneaton-Uttoxeter",          pos = Vector(12.644, 0.96, -5.285) },
        { id = "Burton-on-Trent-Derby",       pos = Vector(9.932, 0.96, -1.112) },
        { id = "Burton-on-Trent-Cannock",     pos = Vector(4.274, 0.96, -1.763) },
        { id = "Tamworth-Nuneaton",           pos = Vector(6.974, 0.96, 1.952) },
        { id = "Birmingham-Tamworth",         pos = Vector(3.035, 0.96, 0.613) },
        { id = "Cannock-Walsall",             pos = Vector(1.324, 0.96, -0.099) },
        { id = "Wolverhampton-Cannock",       pos = Vector(-3.743, 0.96, 0.621) },
        { id = "Stone-Cannock",               pos = Vector(-4.264, 0.96, 2.316) },
        { id = "Stafford-Cannock",            pos = Vector(-0.808, 0.96, 3.685) },
        { id = "Stone-Uttoxeter",             pos = Vector(2.477, 0.96, 3.545) },
        { id = "Leek-Stone",                  pos = Vector(-6.275, 0.96, 5.707) },
        { id = "Stafford-Burton-on-Trent",    pos = Vector(0.442, 0.96, 6.879) },
        { id = "Stoke-on-Trent-Stone",        pos = Vector(-1.969, 0.96, 8.921) },
        { id = "Derby-Tamworth",              pos = Vector(5.863, 0.96, 8.483) },
        { id = "Uttoxeter-Derby",             pos = Vector(8.926, 0.96, 5.836) },
        { id = "Derby-Nottingham",            pos = Vector(11.245, 0.96, 9.988) },
        { id = "Derby-Belper",                pos = Vector(9.337, 0.96, 11.751) },
        { id = "Uttoxeter-Stoke-on-Trent",    pos = Vector(4.925, 0.96, 14.416) },
        { id = "Stafford-Stoke-on-Trent",     pos = Vector(-1.007, 0.96, 14.270) },
        { id = "Stoke-on-Trent-Leek",         pos = Vector(-4.821, 0.96, 10.058) },
        { id = "Shrewsbury-Warrington",        pos = Vector(-5.131, 0.96, 13.742) },
    }

    for _, entry in ipairs(LINK_POSITIONS) do
        local data = {
            position = entry.pos,
            tag = "link_" .. entry.id,
        }
        SnapMap.byLinkId[entry.id] = data
        SnapMap.byTag["link_" .. entry.id] = data
    end

    if printToAll then
        local cityCount = 0
        for _ in pairs(SnapMap.byCityCenter) do cityCount = cityCount + 1 end
        local linkCount = 0
        for _ in pairs(SnapMap.byLinkId) do linkCount = linkCount + 1 end
        printToAll("[SnapMap] loaded " .. count .. " slots in " .. cityCount .. " cities, " .. linkCount .. " links")
    end
end

--- Find the nearest city to a world position (2D, ignoring Y).
-- @param worldPos Vector or table
-- @param threshold number max 2D distance
-- @return string cityName or nil
function SnapMap.findNearestCity(worldPos, threshold)
    local best = nil
    local bestDist = threshold or 3.0

    for cityName, center in pairs(SnapMap.byCityCenter) do
        local dist = SnapMap._distance(worldPos, center)
        if dist < bestDist then
            bestDist = dist
            best = cityName
        end
    end
    return best
end

--- Find the N nearest cities to a world position (2D, ignoring Y).
-- @param worldPos Vector or table
-- @param count number how many cities to return
-- @return table array of city names sorted by distance
function SnapMap.findNearestCities(worldPos, count)
    local all = {}
    for cityName, center in pairs(SnapMap.byCityCenter) do
        local dist = SnapMap._distance(worldPos, center)
        all[#all + 1] = { name = cityName, dist = dist }
    end
    table.sort(all, function(a, b) return a.dist < b.dist end)
    local result = {}
    for i = 1, math.min(count or 2, #all) do
        result[i] = all[i].name
    end
    return result
end

--- Get world position for a building slot
function SnapMap.getPositionForSlot(slotId)
    local data = SnapMap.bySlotId[slotId]
    return data and data.position or nil
end

--- Get world position for a route link
function SnapMap.getPositionForLink(linkId)
    local data = SnapMap.byLinkId[linkId]
    return data and data.position or nil
end

--- Find the nearest game position to a world coordinate
-- Returns { type = "slot"|"link", id = "..." } or nil
function SnapMap.findNearestPosition(worldPos, threshold)
    local nearest = nil
    local nearestDist = threshold or 2.0
    local bestSlot = nil
    local bestDist = 999

    for slotId, data in pairs(SnapMap.bySlotId) do
        local dist = SnapMap._distance(worldPos, data.position)
        if dist < bestDist then
            bestDist = dist
            bestSlot = slotId
        end
        if dist < nearestDist then
            nearestDist = dist
            nearest = { type = "slot", id = slotId }
        end
    end

    for linkId, data in pairs(SnapMap.byLinkId) do
        local dist = SnapMap._distance(worldPos, data.position)
        if dist < nearestDist then
            nearestDist = dist
            nearest = { type = "link", id = linkId }
        end
    end

    if printToAll then
        printToAll("[SnapMap] nearest=" .. tostring(bestSlot) .. " dist=" .. string.format("%.2f", bestDist) .. " matched=" .. tostring(nearest ~= nil))
    end
    return nearest
end

--- 2D distance between two positions (X/Z only, ignoring Y height)
-- onObjectDrop fires while tile is still in the air, so Y distance is unreliable
function SnapMap._distance(a, b)
    local dx = (a.x or a[1]) - (b.x or b[1])
    local dz = (a.z or a[3]) - (b.z or b[3])
    return math.sqrt(dx*dx + dz*dz)
end

return SnapMap
