local SnapMap = {}

SnapMap.byTag = {}      -- tag string → { position, rotation, snapIndex }
SnapMap.bySlotId = {}   -- "Birmingham_cotton_1" → snap data
SnapMap.byLinkId = {}   -- "Birmingham-Coventry" → snap data

--- Scan a board object's snap points and build all mappings
-- Snap point tags follow format:
--   "city_Birmingham_1" for building slots
--   "link_Birmingham-Coventry" for route links
function SnapMap.buildFromObject(boardObject)
    SnapMap.byTag = {}
    SnapMap.bySlotId = {}
    SnapMap.byLinkId = {}

    local snaps = boardObject.getSnapPoints()
    for i, snap in ipairs(snaps) do
        local tag = snap.tags and snap.tags[1] or nil
        if tag then
            local data = {
                position = boardObject.positionToWorld(snap.position),
                rotation = snap.rotation,
                snapIndex = i,
                tag = tag,
            }
            SnapMap.byTag[tag] = data

            if tag:sub(1, 5) == "city_" then
                local slotId = tag:sub(6)
                SnapMap.bySlotId[slotId] = data
            elseif tag:sub(1, 5) == "link_" then
                local linkId = tag:sub(6)
                SnapMap.byLinkId[linkId] = data
            end
        end
    end
end

--- Build slot mappings from hardcoded positions.
-- Positions measured from the reference mod's save-level snap points.
-- This avoids using TTS Tags (which restrict snap behavior).
function SnapMap.buildFromGlobal()
    SnapMap.byTag = {}
    SnapMap.bySlotId = {}
    SnapMap.byLinkId = {}

    -- Hardcoded: snap point world position -> BoardData slot ID
    -- Generated by scripts/build_snap_tags.py
    local SLOT_POSITIONS = {
        -- Belper
        { id = "Belper_cotton_1",       pos = Vector(7.299, 0.96, 13.939) },
        { id = "Belper_manufacturer_1", pos = Vector(8.955, 0.96, 13.939) },
        { id = "Belper_pottery_1",      pos = Vector(10.584, 0.96, 13.939) },
        -- Birmingham
        { id = "Birmingham_cotton_1",      pos = Vector(3.743, 0.96, -6.824) },
        { id = "Birmingham_manufacturer_1",pos = Vector(3.764, 0.96, -5.244) },
        { id = "Birmingham_iron_1",        pos = Vector(5.386, 0.96, -6.817) },
        { id = "Birmingham_manufacturer_2",pos = Vector(5.414, 0.96, -5.223) },
        -- Burton-on-Trent
        { id = "Burton-on-Trent_brewery_1",pos = Vector(10.171, 0.96, -7.885) },
        { id = "Burton-on-Trent_brewery_2",pos = Vector(10.990, 0.96, -6.282) },
        { id = "Burton-on-Trent_coal_1",   pos = Vector(11.802, 0.96, -7.864) },
        -- Cannock
        { id = "Cannock_coal_1",         pos = Vector(-1.692, 0.96, 1.758) },
        { id = "Cannock_manufacturer_1", pos = Vector(-0.032, 0.96, 1.781) },
        -- Coalbrookdale
        { id = "Coalbrookdale_iron_1",    pos = Vector(-10.200, 0.96, -2.829) },
        { id = "Coalbrookdale_iron_2",    pos = Vector(-9.368, 0.96, -1.263) },
        { id = "Coalbrookdale_brewery_1", pos = Vector(-8.530, 0.96, -2.829) },
        -- Coventry
        { id = "Coventry_pottery_1",      pos = Vector(2.114, 0.96, -10.818) },
        { id = "Coventry_manufacturer_1", pos = Vector(3.773, 0.96, -10.818) },
        -- Derby
        { id = "Derby_cotton_1",       pos = Vector(8.429, 0.96, 8.222) },
        { id = "Derby_brewery_1",      pos = Vector(9.234, 0.96, 9.794) },
        { id = "Derby_manufacturer_1", pos = Vector(10.044, 0.96, 8.203) },
        -- Dudley
        { id = "Dudley_coal_1", pos = Vector(-6.169, 0.96, -9.017) },
        { id = "Dudley_iron_1", pos = Vector(-4.555, 0.96, -9.001) },
        -- Kidderminster
        { id = "Kidderminster_cotton_1", pos = Vector(-3.722, 0.96, -5.508) },
        { id = "Kidderminster_cotton_2", pos = Vector(-2.096, 0.96, -5.496) },
        -- Leek
        { id = "Leek_cotton_1",       pos = Vector(-7.521, 0.96, 8.399) },
        { id = "Leek_manufacturer_1", pos = Vector(-5.888, 0.96, 8.390) },
        -- Nuneaton
        { id = "Nuneaton_manufacturer_1", pos = Vector(5.674, 0.96, 4.249) },
        { id = "Nuneaton_cotton_1",       pos = Vector(7.303, 0.96, 4.249) },
        -- Redditch
        { id = "Redditch_coal_1", pos = Vector(-5.710, 0.96, -13.405) },
        { id = "Redditch_iron_1", pos = Vector(-4.074, 0.96, -13.389) },
        -- Stafford
        { id = "Stafford_manufacturer_1", pos = Vector(1.098, 0.96, 14.439) },
        { id = "Stafford_pottery_1",      pos = Vector(2.732, 0.96, 14.424) },
        -- Stoke-on-Trent
        { id = "Stoke-on-Trent_cotton_1",      pos = Vector(-3.885, 0.96, 11.988) },
        { id = "Stoke-on-Trent_manufacturer_1", pos = Vector(-3.022, 0.96, 13.529) },
        { id = "Stoke-on-Trent_pottery_1",      pos = Vector(-2.225, 0.96, 11.988) },
        -- Stone
        { id = "Stone_cotton_1",       pos = Vector(-4.259, 0.96, 5.207) },
        { id = "Stone_manufacturer_1", pos = Vector(-2.637, 0.96, 5.223) },
        -- Tamworth
        { id = "Tamworth_cotton_1", pos = Vector(1.520, 0.96, 8.990) },
        { id = "Tamworth_coal_1",   pos = Vector(3.181, 0.96, 8.972) },
        -- Uttoxeter
        { id = "Uttoxeter_manufacturer_1", pos = Vector(9.378, 0.96, -3.402) },
        { id = "Uttoxeter_brewery_1",      pos = Vector(11.021, 0.96, -3.395) },
        -- Walsall
        { id = "Walsall_manufacturer_1", pos = Vector(0.314, 0.96, -2.130) },
        { id = "Walsall_brewery_1",      pos = Vector(1.955, 0.96, -2.145) },
        -- Wolverhampton
        { id = "Wolverhampton_manufacturer_1", pos = Vector(-5.350, 0.96, -1.340) },
        { id = "Wolverhampton_manufacturer_2", pos = Vector(-3.743, 0.96, -1.347) },
        -- Worcester
        { id = "Worcester_cotton_1", pos = Vector(6.208, 0.96, -0.016) },
        { id = "Worcester_cotton_2", pos = Vector(7.827, 0.96, 0.012) },
    }

    for _, entry in ipairs(SLOT_POSITIONS) do
        local data = {
            position = entry.pos,
            rotation = { x = 0, y = 180, z = 0 },
            tag = "city_" .. entry.id,
        }
        SnapMap.bySlotId[entry.id] = data
        SnapMap.byTag["city_" .. entry.id] = data
    end
end

--- Get world position for a building slot
function SnapMap.getPositionForSlot(slotId)
    local data = SnapMap.bySlotId[slotId]
    return data and data.position or nil
end

--- Get world position for a route link
function SnapMap.getPositionForLink(linkId)
    local data = SnapMap.byLinkId[linkId]
    return data and data.position or nil
end

--- Find the nearest game position to a world coordinate
-- Returns { type = "slot"|"link", id = "..." } or nil
function SnapMap.findNearestPosition(worldPos, threshold)
    local nearest = nil
    local nearestDist = threshold or 2.0

    for slotId, data in pairs(SnapMap.bySlotId) do
        local dist = SnapMap._distance(worldPos, data.position)
        if dist < nearestDist then
            nearestDist = dist
            nearest = { type = "slot", id = slotId }
        end
    end

    for linkId, data in pairs(SnapMap.byLinkId) do
        local dist = SnapMap._distance(worldPos, data.position)
        if dist < nearestDist then
            nearestDist = dist
            nearest = { type = "link", id = linkId }
        end
    end

    return nearest
end

--- Euclidean distance between two positions (tables with x,y,z or [1],[2],[3])
function SnapMap._distance(a, b)
    local dx = (a.x or a[1]) - (b.x or b[1])
    local dy = (a.y or a[2]) - (b.y or b[2])
    local dz = (a.z or a[3]) - (b.z or b[3])
    return math.sqrt(dx*dx + dy*dy + dz*dz)
end

return SnapMap
